<?php
add_filter( 'vc_autocomplete_grid_filter_product_category_lists_callback', 'actavista_TaxonomyAutocompleteSuggester', 10, 3 );
return array(
	'name'        => esc_html__( 'Grid Filter Product', 'actavista' ),
	'base'        => 'grid_filter_product',
	'icon'        => get_template_directory_uri() . '/assets/images/vc_icon.png',
	'category'    => esc_html__( 'Actavista', 'actavista' ),
	'params'      => array(
		//General Setting
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "autocomplete",
			"heading"     => esc_html__( "Categories", "konia" ),
			"param_name"  => "category_lists",
			"description" => esc_html__( "Select product categories to present in page", "konia" ),
			'query_args'  => array( 'taxonomy' => 'product_cat' ),
			'settings'    => array(
				'multiple'       => true,
				'sortable'       => true,
				'min_length'     => 1,
				'no_hide'        => true,
				'groups'         => true,
				'unique_values'  => true,
				'display_inline' => true,
			),
		),
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "textfield",
			"heading"     => esc_html__( "Number", "konia" ),
			"param_name"  => "product_number",
			"description" => esc_html__( "Enter number of product to show", "konia" ),
		),
		array(
			"type"        => "textfield",
			"group"       => esc_html__( 'General', 'actavista' ),
			"heading"     => esc_html__( "Title Limit", "konia" ),
			"param_name"  => "title_limit",
			"description" => esc_html__( "Enter the number of title words to show post title", "konia" ),
		),
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "dropdown",
			"class"       => "",
			"heading"     => esc_html__( 'Order', 'actavista' ),
			"param_name"  => "order",
			"value"       => array(
				esc_html__( 'Ascending', 'actavista' )  => 'ASC',
				esc_html__( 'Descending', 'actavista' ) => 'DESC',
			),
			"description" => esc_html__( "Select sorting order ascending or descending", 'actavista' ),
		),
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "checkbox",
			"heading"     => esc_html__( "Add to Cart", "konia" ),
			"param_name"  => "show_cart",
			"description" => esc_html__( "Enable to show product add to cart button", "konia" ),
		),
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "checkbox",
			"heading"     => esc_html__( "Quick View", "konia" ),
			"param_name"  => "show_quick",
			"description" => esc_html__( "Enable to show product quick view button", "konia" ),
		),
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "checkbox",
			"heading"     => esc_html__( "Show Discount", "konia" ),
			"param_name"  => "show_discount",
			"description" => esc_html__( "Turn it ON to show product discount label on product thumb", "konia" ),
		),
		array(
			"group"       => esc_html__( 'General', 'actavista' ),
			"type"        => "checkbox",
			"heading"     => esc_html__( "Show Variation", "konia" ),
			"param_name"  => "show_variation",
			"description" => esc_html__( "Turn it ON to show product variation", "konia" ),
		),
		actavista_vc_lg_column(),
		actavista_vc_md_column(),
		actavista_vc_sm_column(),
		actavista_vc_xs_column(),
		actavista_vc_lg_custom_image(),
		actavista_vc_tb_custom_image(),
		actavista_vc_mb_custom_image(),
	),
);
