<?php 
return array(
	'vc_row'  => array(
		array(
			'type'       => 'dropdown',
			'class'      => '',
			'group'      => esc_html__( 'Section Settings', 'actavista' ),
			'heading'    => esc_html__( 'Select Space', 'actavista' ),
			'param_name' => 'gap_select',
			'value'      => array(
				esc_html__( 'From Top and Bottom', 'actavista' ) => 'gap',
				esc_html__( 'Less Space From Top', 'actavista' ) => 'bit-gap',
				esc_html__( 'Less Space From Top and Bottom', 'actavista' ) => 'bit-gap',
				esc_html__( '40 PX Space From Bottom', 'actavista' ) => 'widget-gap',
				esc_html__( 'From Top', 'actavista' )    => 'no-bottom',
				esc_html__( 'From Bottom', 'actavista' ) => 'no-top',
				esc_html__( 'Extra Space From Top', 'actavista' ) => 'extra-top',
				esc_html__( 'Extra Margin From Top', 'actavista' ) => 'no-gap extra-gap-top',
				
				esc_html__( 'No Space', 'actavista' )    => 'no-gap',
			),
			'description'    => esc_html__( 'Select Space for this section.', 'actavista' ),
		),
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Overlap', 'actavista' ),
			'param_name'  => 'overlap_select',
			'value'       => array(
				esc_html__( 'No Overlap', 'actavista' )    => 'no-overlap',
				esc_html__( 'Overlap 130', 'actavista' ) => 'overlap130',
				esc_html__( 'Overlap 70', 'actavista' ) => 'overlap70',
				esc_html__( 'Overlap 35', 'actavista' ) => 'overlap-header',
			),
			'description' => esc_html__( 'Select overlap for this section.', 'actavista' ),
		),
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Column Inner Gap', 'actavista' ),
			'param_name'  => 'inner_gap_option',
			'value'       => array(
				esc_html__( 'No Columns Gap', 'actavista' )    => 'remove-golumns-gap',
				esc_html__( 'Show Columns Gap With Row', 'actavista' )  => 'enable-golumns-gap row',
				esc_html__( 'Show Columns Gap without Row', 'actavista' )  => 'enable-golumns-gap',
			),
			'std'         => 'remove-golumns-gap',
			'description' => esc_html__( 'Select columns gap.', 'actavista' ),
		),
		array(
			'type'        => 'checkbox',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'param_name'  => 'show_container',
			'value'       => array( 'Enable Container Options' => 'true' ),
			'description' => esc_html__( 'Enable to show container options.', 'actavista' ),
		),
		
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Container Type', 'actavista' ),
			'param_name'  => 'container_type',
			'value'       => array(
				esc_html__( 'Select Container Type', 'actavista' )    => '',
				esc_html__( 'Container', 'actavista' )    => 'container',
				esc_html__( 'Container Fluid', 'actavista' ) => 'container-fluid',
				esc_html__( 'Container Fluid WIth Padding', 'actavista' ) => 'container-fluid side-padding',
				
			),
			'description' => esc_html__( 'Select overlap for this section.', 'actavista' ),
			'dependency'  => array(
				'element'   => 'show_container',
				'value'     => 'true',
			),
		),
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Section Background Settings', 'actavista' ),
			'param_name'  => 'bg_settings',
			'value'       => array(
				esc_html__( 'Select Option', 'actavista' )    => '',
				esc_html__( 'Background Colored', 'actavista' ) => 'bg_colored',
				esc_html__( 'Background Image With Layer', 'actavista' )  => 'parallax_imaged',
			),
			'description' => esc_html__( 'Select background option for this section.', 'actavista' ),
		),
		array(
			'type'              => 'attach_image',
			'class'             => '',
			'group'				=> esc_html__( 'Section Settings', 'actavista' ),
			'heading'           => esc_html__( 'Background Image', 'actavista' ),
			'param_name'        => 'parallax_bg_image',
			'description'       => esc_html__( 'Upload background image to show.',  'actavista' ),
			'dependency'  => array(
				'element'   => 'bg_settings',
				'value'     => 'parallax_imaged',
			),
		),
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Image Layer', 'actavista' ),
			'param_name'  => 'image_layer',
			'value'       => array(
				esc_html__( 'No Layer', 'actavista' )    => 'no-layer',
				esc_html__( 'Pink Layer', 'actavista' )  => 'redish',
				esc_html__( 'Black Layer', 'actavista' ) => 'blackish',
				esc_html__( 'Gray Layer', 'actavista' )  => 'grayesh',
				esc_html__( 'Blue Layer', 'actavista' )  => 'bluesh',
				esc_html__( 'Green Layer', 'actavista' ) => 'greenish',
				esc_html__( 'Red Layer', 'actavista' ) => 'redish',
			),
			'description' => esc_html__( 'Select layer color for background image.', 'actavista' ),
			'dependency'  => array(
				'element'   => 'bg_settings',
				'value'     => 'parallax_imaged',
			),
		),
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Opacity', 'actavista' ),
			'param_name'  => 'layer_opacity',
			'value'       => array(
				esc_html__( 'No Opacity', 'actavista' ) => 'no-opacity',
				esc_html__( 'Low Opacity', 'actavista' ) => 'low-opacity',
				esc_html__( 'Extra Low Opacity', 'actavista' ) => 'more-low-opacity',
				
				esc_html__( 'Medium Opacity', 'actavista' )  => 'medium-opacity',
				esc_html__( 'High Opacity', 'actavista' ) => 'high-opacity',
				
			),
			'description' => esc_html__( 'Select layer Opacity for background image.', 'actavista' ),
			'dependency'  => array(
				'element'   => 'bg_settings',
				'value'     => 'parallax_imaged',
			),
		),
		array(
			'type'  => 'dropdown',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'heading'     => esc_html__( 'Select Background Color', 'actavista' ),
			'param_name'  => 'image_bg_color',
			'value'       => array(
				esc_html__( 'Select Background Color', 'actavista' )    => '',
				esc_html__( 'Blue Background', 'actavista' ) => 'full-width',
				esc_html__( 'Light Blue Background', 'actavista' ) => 'light-blue-bg',
				esc_html__( 'Pink Background', 'actavista' ) => 'redish ',
				esc_html__( 'Gray Background', 'actavista' ) => 'gray-bg ',
			),
			'dependency'  => array(
				'element'   => 'bg_settings',
				'value'     => 'bg_colored',
			),
		),
		array(
			'type'        => 'checkbox',
			'class'       => '',
			'group'       => esc_html__( 'Section Settings', 'actavista' ),
			'param_name'  => 'show_box_shadow',
			'value'       => array( 'Enabl merged Columns' => 'true' ),
			'description' => esc_html__( 'Enable to show  merged columns.', 'actavista' ),
		),
	),
);
